const SUPABASE_URL="https://vhpqncvvzwoowhbmlkrm.supabase.co";
const SUPABASE_PUBLIC_KEY = "sb_publishable_RQU1poSEx2EluMP7EOfWFg_QKwxtldb";

function send(res,status,body){res.status(status).json(body);}
async function callRpc(name,payload){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SUPABASE_PUBLIC_KEY,Authorization:`Bearer ${SUPABASE_PUBLIC_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});return {ok:response.ok,data:response.ok?await response.json():null};}
function clean(value,max=1200){return String(value||'').replace(/[<>]/g,'').slice(0,max);}
function personaPrompt(target,contexto){return `Você é pesquisador(a) de comportamento do consumidor imobiliário. Gere uma PERSONA ESTRATÉGICA AUDITÁVEL em português, usando somente os dados fornecidos. A persona é uma composição fictícia de segmento, jamais diagnóstico individual.

Base metodológica: valores de Schwartz e intenção de compra da Teoria do Comportamento Planejado. Use estes referenciais apenas para organizar hipóteses; não afirme validade clínica, não infira atributos sensíveis, raça, religião, saúde, orientação sexual, diagnóstico, condição financeira individual ou intenção certa de compra.

Classifique cada afirmação como evidência, inferência ou hipótese de validação. Não invente estudos, números, fontes nem citações. A confiança deve ser baixa se a equipe não forneceu fonte, amostra e evidência.

Retorne JSON válido SEM markdown com as chaves: nome, titulo, resumo, valores_prioritarios (array), necessidades (array), barreiras (array), jornada (array), evidencias (array), inferencias (array), hipoteses_validacao (array), confianca {score:number,nivel:string,rotulo:string,justificativa:string}, descricao_imagem:string.

DADOS DO TARGET: ${JSON.stringify(target)}
CONTEXTO DO PRODUTO: ${JSON.stringify(contexto)}`;}
async function openAIChat(prompt){const response=await fetch("https://api.openai.com/v1/chat/completions",{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4o-mini",temperature:0.25,response_format:{type:"json_object"},messages:[{role:"system",content:"Você responde somente JSON válido."},{role:"user",content:prompt}]})});if(!response.ok)throw new Error(`OpenAI retornou HTTP ${response.status}.`);const payload=await response.json();return JSON.parse(payload.choices?.[0]?.message?.content||'{}');}
async function generateImage(persona){const prompt=`Retrato editorial realista, caloroso e profissional de uma pessoa brasileira completamente fictícia, representando uma persona de mercado imobiliário. ${clean(persona.descricao_imagem||persona.resumo,900)}. Fundo neutro com leve profundidade, vestimenta cotidiana profissional, enquadramento de busto, iluminação natural suave. Não incluir texto, marcas, logotipos, pessoas identificáveis ou características sensíveis. Esta é uma ilustração de segmento, não uma pessoa real.`;const response=await fetch("https://api.openai.com/v1/images/generations",{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-1",prompt,size:"1024x1024"})});if(!response.ok)throw new Error(`A geração de imagem retornou HTTP ${response.status}.`);const payload=await response.json();const b64=payload.data?.[0]?.b64_json;if(!b64)throw new Error('O provedor não retornou uma imagem persistível.');return `data:image/png;base64,${b64}`;}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","content-type");res.setHeader("Access-Control-Allow-Methods","POST, OPTIONS");if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=="POST")return send(res,405,{error:"Método não permitido."});const {tipo,codigo,senha,papel,target,contexto,persona}=req.body||{};if(!tipo||!codigo||!senha||!papel)return send(res,400,{error:"Parâmetros obrigatórios ausentes."});const isTeacher=String(papel).toLowerCase()==='professor';const auth=await callRpc(isTeacher?'entrar_professor':'verificar_senha_aluno',isTeacher?{p_codigo:codigo,p_senha_prof:senha}:{p_codigo:codigo,p_senha_aluno:senha});if(!auth.ok||!auth.data)return send(res,403,{error:"Acesso à turma não autorizado."});if(!process.env.OPENAI_API_KEY)return send(res,503,{error:"Persona por IA ainda não foi configurada no servidor."});try{if(tipo==='persona'){if(!target)return send(res,400,{error:"Dados do Target ausentes."});return send(res,200,{persona:await openAIChat(personaPrompt(target,contexto||{}))});}if(tipo==='imagem'){if(!persona)return send(res,400,{error:"Gere primeiro a persona textual."});const imagemData=await generateImage(persona);if(imagemData.length>1500000)return send(res,413,{error:"A imagem ficou grande demais para o dossiê. Tente novamente."});return send(res,200,{imagemData});}return send(res,400,{error:"Tipo de geração inválido."});}catch(error){return send(res,502,{error:error.message||"Não foi possível gerar a persona."});}}
